instructlab/ui

MAINTAINERS.md, README.md
=> Update project readme file with meeting, slack and maintainers details

src/app/api/pr/knowledge/route.ts, src/app/api/pr/skill/route.ts, src/app/edit-submission/knowledge/[id]/page.tsx, src/app/edit-submission/skill/[id]/page.tsx, src/components/Contribute/Knowledge/index.tsx, src/components/Contribute/Skill/index.tsx, src/types/index.ts, src/utils/github.ts
- Set the length in yaml.dump to enforce a multiline formatting.
- Pass interfaces to the submission APIs to clean up the number of arguments sent and reduce bad code, e.g. `KnowledgeYamlData` and `SkillYamlData` along with `AttributionData`.
- Fix amend submissions to add DCO sign-off.
- Have the user add an email to their edit submission because a GitHub account does not have to have an associated email to look up. Same with name for DCO.
- Add the ability for the user to specify the submission file path. Sanitizes the file path to be usable. On edit, the file path is pulled in for editing from the existing PR. If amended, the files are added to the new git tree with the new file path. Example: https://github.com/brents-pet-robot/taxonomy-sub-testing/pull/117/files
Closes #47 
Closes …
=> Bug fixes: amend DCO sign-off and pass data structures to the submission routes

src/components/Contribute/Knowledge/index.tsx, src/components/Contribute/Knowledge/knowledge.css, src/components/Contribute/Skill/index.tsx, src/components/Contribute/Skill/skill.css
This does not solve the discrepancy regarding why the dev and prod css is different. However, the buttons now look a consistent style by removing the specific class for the buttons
=> removing the css for the individual buttons within the action group and let the form do the styling

Containerfile, package-lock.json, src/app/api/envConfig/route.ts, src/app/api/pr/knowledge/route.ts, src/app/api/pr/skill/route.ts, src/app/edit-submission/knowledge/[id]/page.tsx, src/app/edit-submission/skill/[id]/page.tsx, src/utils/github.ts
This PR fixes following issues
- Don't use process.env for client side code. Rely on getting these env variable from server side. In the container deployment, we need to read these environment variables dynamically, because building the application while launching the container requires privileges.
- Fix the default location for qna/attribution files of skill and knowledge contribution
- Update the npm dependencies.
Fixes #60 
Fixes #61
=> Fix environment variable reading issue in client side code

src/app/layout.tsx
Individual pages can override the title by exporting their own metadata object.
=> Use the nextjs metadata api to set tab/page titles

src/app/api/pr/knowledge/route.ts, src/app/api/pr/skill/route.ts, src/app/edit-submission/knowledge/[id]/page.tsx, src/app/edit-submission/skill/[id]/page.tsx, src/components/Contribute/Knowledge/index.tsx, src/components/Contribute/Knowledge/knowledge.css, src/components/Contribute/Skill/index.tsx, src/types/index.ts, src/utils/yamlConfig.ts
- Handle null values as custom blank entries. js-yaml doesn't offer a config knob for empty values so this extends it to replace all single and double quotes along with a null value to be an empty line.
Closes #62
=> Add a yaml format util for handling formatting

src/utils/yamlConfig.ts
- Custom yaml for multiline white spaces.
- Single line will single quote by default.
- If the context field is null, do not add it to the skill yaml.
Closes #70 
Closes #72 
Example output: https://github.com/brents-pet-robot/taxonomy-sub-testing/pull/139/files
=> Remove trailing spaces and empty contexts from yaml

docs/development.md
Section in the development.md instructions for running the markdown linter via makefile. Also link out to podman instructions which is a dependency of this functionality.
=> Instructions for dev markdown file linting

src/app/playground/chat/page.tsx
A user selects the model they want to chat to. On a page refresh or change the system changes the model selected back to the Granite 7B model. I was using a different one and did not expect this behaviour and therefore the API calls to the chat server were incorrect.
To address this I have:
1) Stopped the first model in the drop down list being selected by default on page load. The model selector now has no model selected.
2) If a user tries to submit a query with no model selected then an error message appears to communicate this.
3) When the user selects the model they desire the error message clears.
I have noticed that the empty prompt in a request is not communicated to the user. I will deal with this in -> https://github.com/instructlab/ui/issues/78
Fixes #53
=> Issue around the selected model silently changing on refresh or page change

src/app/playground/chat/page.tsx
on merge, close #124 
When clicking the clear text button mid answer, the application won't crash anymore.
However it is still generating the answer, so when another question is asked, it will continue answering the previous question.
e.g. I asked to give a short description of Sherlock Holmes before clearing the text.
=> UI Crash on clear chat button fix

src/app/api/pr/knowledge/route.ts, src/components/Contribute/Knowledge/Submit/Submit.tsx, src/components/Contribute/Knowledge/index.tsx
Newly created PR doesn't have title and body
Newly created PR doesn't have commit title message
PR link now has associated URL, so user don't have to copy paste the URL
=> Fix follow knowledge form related issues

src/app/login/githublogin.css, src/components/Dashboard/index.tsx
- Changed the label chips to the patternfly label component
- Sort by creation date
- Made the open PR link to a button
=> Convert the dashboard list to horizontally stacked chips

src/components/Contribute/Knowledge/AttributionInformation/AttributionInformation.tsx, src/components/Contribute/Knowledge/AuthorInformation/AuthorInformation.tsx, src/components/Contribute/Knowledge/DocumentInformation/DocumentInformation.tsx, src/components/Contribute/Knowledge/FilePathInformation/FilePathInformation.tsx, src/components/Contribute/Knowledge/KnowledgeDescription/KnowledgeDescriptionContent.tsx, src/components/Contribute/Knowledge/KnowledgeInformation/KnowledgeInformation.tsx, src/components/Contribute/Knowledge/KnowledgeQuestionAnswerPairs/KnowledgeQuestionAnswerPairs.tsx, src/components/Contribute/Knowledge/index.tsx, src/components/Contribute/Knowledge/validation.tsx, src/components/Contribute/Skill/index.tsx, src/components/PathService/PathService.tsx
*.* Disable submit/download button if user adds new seed example or Q&A pair
*.* Reset all validation conditions after the successful submit of the knowledge
=> Knowledge fixes

pathservice/cmd/pathservice.go, src/app/api/pr/skill/route.ts, src/app/edit-submission/knowledge/[id]/page.tsx, src/app/edit-submission/skill/[id]/page.tsx, src/components/Contribute/Skill/AttributionInformation/AttributionInformation.tsx, src/components/Contribute/Skill/AuthorInformation/AuthorInformation.tsx, src/components/Contribute/Skill/FilePathInformation/FilePathInformation.tsx, src/components/Contribute/Skill/SkillsDescription/SkillsDescriptionContent.tsx, src/components/Contribute/Skill/SkillsInformation/SkillsInformation.tsx, src/components/Contribute/Skill/SkillsSeedExample/SkillsSeedExample.tsx, src/components/Contribute/Skill/Submit/Submit.tsx, src/components/Contribute/Skill/Update/Update.tsx, src/components/Contribute/Skill/validation.tsx
-  remove redundant description text from individual seed example 
- add link to the seed examples documentation page for user help 
- Rename File path to Taxonomy Directory Path and update the description.
- Taxonomy directory path will only show directories within compositional_skills directory in taxonomy repo. Taxonomy repo doesn't allow contribution to foundational_skills at this point of time.
- Update Skill contribution page head text with related links.
Fixes #148 
Fixes #154
=> Skill form improvements

src/components/Contribute/Knowledge/AttributionInformation/AttributionInformation.tsx, src/components/Contribute/Knowledge/AuthorInformation/AuthorInformation.tsx, src/components/Contribute/Knowledge/DocumentInformation/DocumentInformation.tsx, src/components/Contribute/Knowledge/FilePathInformation/FilePathInformation.tsx, src/components/Contribute/Knowledge/KnowledgeInformation/KnowledgeInformation.tsx, src/components/Contribute/Knowledge/KnowledgeQuestionAnswerPairs/KnowledgeQuestionAnswerPairs.tsx, src/components/Contribute/Knowledge/KnowledgeSeedExample/KnowledgeSeedExample.tsx, src/components/Contribute/Knowledge/index.tsx, src/utils/yamlConfig.ts
- Remove buttons to add new QnA pair and seed examples, because backend ignores more than 3 QnA pair per context and more than 5 seed examples.
- Replace info to information
=> Improves following in the knowledge submission form

src/components/GithubAccessPopup/index.tsx
=> Fix github warning popup content formatting

src/app/api/pr/knowledge/route.ts, src/app/api/pr/skill/route.ts, src/app/edit-submission/knowledge/[id]/page.tsx, src/app/edit-submission/skill/[id]/page.tsx, src/components/Contribute/Knowledge/DownloadYaml/DownloadYaml.tsx, src/components/Contribute/Knowledge/Submit/Submit.tsx, src/components/Contribute/Knowledge/Update/Update.tsx, src/components/Contribute/Knowledge/ViewDropdown/ViewDropdown.tsx, src/components/Contribute/Knowledge/index.tsx, src/components/Contribute/Knowledge/validation.tsx, src/components/Contribute/Skill/DownloadYaml/DownloadYaml.tsx, src/components/Contribute/Skill/Submit/Submit.tsx, src/components/Contribute/Skill/Update/Update.tsx, src/components/Contribute/Skill/ViewDropdown/ViewDropdown.tsx, src/components/Contribute/Skill/index.tsx, src/components/Contribute/Skill/validation.tsx, src/components/Dashboard/index.tsx, src/types/const.ts, src/types/index.ts, src/utils/github.ts
taxonomy clone is not present in user github account.
UI attempts to create the clone, but the clone can take some time to finish. When UI attempts to get the base sha of the repo's main branch it fails because the repository is empty.
Add retry logic to check the bash sha every 5 seconds and make 10 attempts. If clone takes more than 50 seconds it fails.
In this specific scenario, when user creates it's first contribution, it can take a bit longer because of the repo cloning. Without any notification, this wait time might look like a no-op to the user. To address this added a spinner with an alter message that notifies user that the submission is in progress.
Patch also includes refactoring of duplicate code present across api/skill and api/knowledge.
Fixes #52
=> Knowledge and Skill contribution fails if the initial

src/components/Dashboard/index.tsx
I didn't change this from the patternfly example 🤦
=> Fix ilab link in empty state dashboard

src/components/Dashboard/index.tsx
Show a modal with spinner while retrieving the data from github.
Currently it shows the empty state and then once the PRs are
pulled, it shows the list. This flicker of empty list always
happen whenever we switch from any other menu item to Dashboard.
Also it logs the error message rather than showing it as a div on the page.
We need a notification button to show these errors/info.
=> Log the error, rather than rendering it

src/app/page.tsx, src/components/GithubAccessPopup/index.tsx
=> Fetch PR data once user accepts the warning conditions

.github/dependabot.yml
fixes https://github.com/instructlab/ui/issues/22
Enabling dependabot for the repository. The configuration aims at addressing Docker images, npm packages, and go modules.
Summary of changes:
- Used Grouping: Dependabot will group certain dependencies with the keyword “group”.
- For `github-actions`, I just used a single group, and used a wildcard pattern to achieve like an "everything group".
- Limiting the security updates to the dependencies and ignore dev dependencies. Highlighted in `dependency-type: "production"`
=> 22: Add configuration options for introducing dependabot

src/components/Contribute/Knowledge/AttributionInformation/AttributionInformation.tsx
Existing implementation: The existing form places the URL after the name requiring user to manually enter all fields
UX recommendations
- Place URL as the first field
- Update AttributionInformation.tsx file to place the URL text input as the first field within the attribution form section. 
- [IL Issue](https://github.com/instructlab/ui/issues/153)
=> 153: Attribute information improvements

src/components/Contribute/Knowledge/FilePathInformation/FilePathInformation.tsx, src/components/Contribute/Knowledge/KnowledgeQuestionAnswerPairs/KnowledgeQuestionAnswerPairs.tsx, src/components/Contribute/Knowledge/index.tsx, src/components/Contribute/Knowledge/validation.tsx
After discussion with Taxonomy Traiger team, it was concluded that at this point of time, having a 750 max words limit is a better constraint compared to 750 char. 
Ideally this constraints should be enforced based on the number of tokens. Each model can have it's own way of splitting the string in the tokens, so determining number of tokens in any string depends on the model. Having a tokenizer service, that exposes a REST API to return the numbers of tokens in the provided string based on the base model, would be a really useful service in this scenario. We can leverage that to enforce the limits in terms of token.
=> Change limit from 750 char to words

next-env.d.ts, src/components/AppLayout.tsx
=> Adjust flex layout to avoid help and avatar stacking in masthead

src/components/AppLayout.tsx
- The header and left sidebar of the application are not responsive, causing layout issues and reduced usability on smaller window sizes and mobile devices
- Update Patternfly components to make use of the built-in responsive capabilities for header and sidebar.
https://github.com/user-attachments/assets/6babfaec-6f01-406f-810e-f08b83196a5a
=> 194: Implement built-in responsiveness for Sidebar.

.github/workflows/actionlint.dockerfile, .github/workflows/actionlint.yml, .github/workflows/matchers/actionlint.json
this is an action we use in other instructlab repos to lint github actions within repos to ensure new or changed actions will run without issue
=> ci: add linter for github actions

.gitignore, docs/development.md, package-lock.json, package.json, playwright.config.ts, tests/auth.setup.ts, tests/login.spec.ts
fixes https://github.com/instructlab/ui/issues/23
Summary of changes:
- Setup Playwright (installed packages, setup configuration)
- Created a simple setup test that performs a real login with an e2e account and saves the storage state so the next tests can run in an authenticated state. Using env variables for username, and password so these can be supplied from the user. 
- Basic tests for login page
- NPM scripts for execution on local
- Docs in development markdown for running these tests locally
Example report after running the tests locally:
=> 23: Global setup for Playwright, and some basic Playwright UI tests 

.gitignore, docs/development.md, package-lock.json, package.json, playwright.config.ts, tests/auth.setup.ts, tests/login.spec.ts
…(#254)
* fix merge conflicts -s
* basic configuration for tests execution
* basic tests in place
* some refactoring for basic tests
* basic playwright setup
* add docs for playwright tests
* updates per failures on linting
* fix linting errors
---------
=> Cherry Pick 23: Global setup for Playwright, and some basic Playwright UI tests 

src/app/login/githublogin.tsx
Update title and message of the Join InstructLab on GitHub modal
=> cherry-pick:Update content of Join InstructLab on GitHub modal

README.md, argocd/overlays/applicaitons/qa.yaml
This should point our QA manifests back to upstream and add some simple documentation on using the ss operator / controller.
After this, we can test cutting a new release and see if it redeploys
=> point back to upstream and add SS docs

src/app/login/githublogin.css, src/app/login/locallogin.tsx, src/app/login/page.tsx
Changes the local login page from the default Patternfly form to match the SaaS login when started in dev mode. I don't really like the text but we can set it to whatever in another PR:
This also breaks out locallogin in a similar pattern to github login to resolve hydration errors from nextjs v15.
=> Align the local dev login page with the Oauth login page

package-lock.json, package.json, src/app/login/githublogin.tsx, src/app/login/locallogin.tsx, src/app/playground/chat/page.tsx, src/app/playground/endpoints/page.tsx, src/components/AboutModal/AboutModal.tsx, src/components/AppLayout.tsx, src/components/Contribute/EditKnowledge/EditKnowledge.tsx, src/components/Contribute/EditSkill/EditSkill.tsx, src/components/Contribute/Knowledge/DocumentInformation/DocumentInformation.tsx, src/components/Contribute/Knowledge/KnowledgeDescription/KnowledgeDescriptionContent.tsx, src/components/Contribute/Knowledge/UploadFile.tsx, src/components/Contribute/Knowledge/index.tsx, src/components/Contribute/Skill/SkillsDescription/SkillsDescriptionContent.tsx, src/components/Contribute/Skill/SkillsSeedExample/SkillsSeedExample.tsx, src/components/Contribute/Skill/index.tsx, src/components/CopyToClipboardButton/index.tsx, src/components/Dashboard/index.tsx, src/components/Experimental/ContributeLocal/Knowledge/index.tsx, src/components/Experimental/ContributeLocal/Skill/index.tsx, src/components/Experimental/DashboardLocal/index.tsx, src/components/GithubAccessPopup/index.tsx, src/components/UserMenu/ThemePreference.tsx, src/components/YamlCodeModal/index.tsx
- Themes are now done via Tokens. The current theme is no longer honored and will need to be resolved via design tokens: https://www.patternfly.org/tokens/about-tokens
Examples:
- Code modal popup formatting needs work:
Closes #337
=> Migrate to Patternfly v6

.github/workflows/pr-images.yml, .github/workflows/release-images.yml, deploy/k8s/base/pathservice/deployment.yaml, deploy/k8s/base/ui/deployment.yaml
Previous workflow failed, see logs: https://github.com/instructlab/ui/actions/runs/11862220666/job/33061144701#step:13:213.
The issue here was that the extracted tag data from one of the `"${{ steps.ghcr_ui_meta.outputs.tags }}"` values resolves to something like `quay.io/instructlab-ui/pathservice:main` where as the combined tags got only the image tag, resolving to `pr-334`. This is why it would complain because it thinks the whole image ref was pr-334 and so it couldn't build. I have refactored my approach to the tagging which I think should work, and refactored for simplicity.
=> remove combining tags steps and restructure multiple tags

.github/workflows/pr-images.yml, .github/workflows/release-images.yml
Next workflow failed due to lack of access to the actor's (whoever merges the MR) ssh key. Moving to just signoff but not ssh signature.
=> removing -S tack from commit, signing requires ssh key

.github/workflows/pr-images.yml, .github/workflows/release-images.yml
cc @vishnoianil @nerdalert 
Workflow was not working due to auth, It seems github actions bot cannot push to main. I have opted to reconstruct the remote using the `secrets.GITHUB_TOKEN`, although I dont know what token this or what permissions it has. I also removed the force push to be on the safe side.
Ref to previous failed job run: https://github.com/instructlab/ui/actions/runs/11882953745/job/33109072941
Logs:
```
[main c17732d] [CI AUTOMATION]: Bumping QA UI image to tag: pr-347
1 file changed, 1 insertion(+), 1 deletion(-)
remote: Permission to instructlab/ui.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/instructlab/ui/': The requested URL returned error: [40](https://github.com/instructlab/ui/actions/runs/11882953745/job/33109072941#step:16:41)3 …
```
=> removing force push and push through token

src/components/AppLayout.tsx
- After the patternfly upgrade it looked a little weird aligned closer to the center.
=> Move the Instructlab header next to the logo

pathservice/Containerfile, src/Containerfile
@cooktheryan this should fix both those issues.
cc @nerdalert @vishnoianil
=> using unauthed image for PS + change package*.json file permissions

.github/workflows/pr-images.yml, .github/workflows/release-images.yml
cc @nerdalert @vishnoianil 
This will use the `platform-engineering-bot` user which I have enabled to push to main, and setup the `BOT_PAT` secret with its personal access token.
=> use platform-engineering-bot for image workflows

.devcontainer/Containerfile, .devcontainer/devcontainer.json, Makefile, docs/development.md
Addresses: #361 
cc @vishnoianil @nerdalert 
Everything works like a dream. I motion we publish this image to the quay org. Also if you think of any other cool binaries we could stuff in here that would be great. I was thinking maybe `ngrok` if they want a free way to emulate HTTPS routes and share one devs build to another
=> initial devcontainer implementation

.github/workflows/pr-images.yml, .github/workflows/release-images.yml
basically what is happening, is that the pathservice image bump commit merges, and this causes conflicts for the UI one. There for I added `git pull --ff-only` to the job to allow it to fast forward to that commit, and avoid conflicts
=> allow pull --ff-only to avoid collisions

next.config.js, src/app/login/githublogin.tsx
This should fix build warnings ([link](https://github.com/instructlab/ui/actions/runs/11940281178/job/33283099011#step:11:554)), ex:
```
#20 15.50  ⚠ Invalid next.config.js options detected: 
#20 15.51  ⚠     Unrecognized key(s) in object: 'missingSuspenseWithCSRBailout' at "experimental"
#20 15.51  ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
#20 15.67 Attention: Next.js now collects completely anonymous telemetry regarding usage.
#20 15.67 This information is used to shape Next.js' roadmap and prioritize features.
#20 15.67 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#20 15.67 https://nextjs.org/telemetry
#20 15.67 
#20 16.77    ▲ Next.js 15.0.3
```
=> fixing missingSuspenseWithCSRBailout warnings with nextjs 15 bump

.github/workflows/pr-images.yml, .github/workflows/release-images.yml
The issue with this was that I was modifying the manifests with the pr tag before `pull`ing to fast forward and pick up any other CI changes. Here is an example log:
```
From https://github.com/instructlab/ui
49cad10..9e14ad2  main        -> origin/main
* [new branch]      dependabot/npm_and_yarn/main/fortawesome/fontawesome-svg-core-6.7.1 -> origin/dependabot/npm_and_yarn/main/fortawesome/fontawesome-svg-core-6.7.1
* [new branch]      release-1.0 -> origin/release-1.0
* [new branch]      streamline-release-images-workflow -> origin/streamline-release-images-workflow
* [new tag]         v1.0.0-beta.0 -> v1.0.0-beta.0
* [new tag]         v1.0.0-beta.1 -> v1.0.0-beta.1
* [new tag]         v1.0.0-beta.2 -> v1.0.0-beta.2
* [new tag]         v1.0.0-beta.3 -> v1.0.0-beta.3
error: Your local …
```
=> [FIX] move fast-forward pull before changes to avoid conflict

.github/workflows/devcontainer-image.yml
This should build and publish our devcontainer images through CI.
Relates to: #361 and #366 .
=> building and publishing devcontainer images in CI

.github/workflows/pr-images.yml
This PR, while does not speedup our workflows, makes it considerably less code, and easier to update. We should consider if we want something like this conceptually.
=> refactor image workflows to parallel matrix

src/app/api/local/pr/knowledge/route.ts
- Fixes the local mode formatting to pass taxonomy linting
=> Fix local git submissions by casting to KnowledgeYamlData

.github/workflows/pr-images.yml
Reverts instructlab/ui#363. I will continue to work on this implementation but it turns out you cannot specify a key and a value and combine them. Ill have to think on this
=> Revert "refactor image workflows to parallel matrix"

.github/workflows/pr-images.yml
Currently what is happening: A PR gets merged, which through CI triggers a commit to bump and push the deployment manifests with new updated image tag, which triggers the same workflow. At this point I previously chose to fail the workflow but that looks ugly in CI, as well as produces false positives for debugging - making me think some of those actions are actually failing and not just cutting short as intended. This code change should make it such the workflow still succeeds it would just only have 1 job. This is the only job that needs it as all the others either look for different push paths or are triggered on release.
=> remove CI_AUTOMATION workflow errors by checking skip

.github/workflows/pr-images.yml
https://github.com/instructlab/ui/actions/runs/12165643601/job/33931228650 should have ran, I believe this is because of github_output vs github_env
=> use github_output over github_env

README.md
This updates our readme to include a link to our discord, as part of this epic:
https://github.com/instructlab/community/issues/409
Signed-off-by: Oleg S <97077423+RobotSail@users.noreply.github.com>
=> Update readme to include discord

argocd/overlays/applicaitons/umami.yaml
Relates to #406.
In the last PR I made the overlays, forgot to update the Argocd app.
=> updating umami argocd app to use prod overlay and cluster

argocd/overlays/applicaitons/umami.yaml
one more update @vishnoianil 
Argocd cannot decrypt the sealed secret on the QA cluster because of course this sealed-secret was created and encrypted on the Prod cluster. This change should update our Umami deployment to be deployed on the prod cluster which is what we want anyway
=> deploying to prod cluster

src/components/Dashboard/Native/dashboard.tsx
- Currently edit will call prompt the user to delete the submission.
- Pop a not implemented modal instead of calling delete submission until it is implemented.
Just close it if I am missing something on this!
=> no-op edit submission instead of calling delete submission

.dockerignore, next-env.d.ts, package-lock.json, package.json, src/Containerfile
The `make ui-image` target was not working, as well as containerized UI builds due to 2 issues.
First is a permission issue, the `default` user didn't own the `node_modules` directory so `npm install` would fail due to lacking write permission. The fix here is to create an empty `node_modules` dir and give `default` write access on it. Another related optimization is that you should never bring `node_modules` from your host system because of potential cross-platform issues, so that has been `.dockerignore`ed.
Secondly there was a dependency missmatch that needed to be resolved: ` ⚠ Mismatching @next/swc version, detected: 15.0.3 while Next.js is on 15.1.0. Please ensure these match`. After this everything builds fine.
=> fixing make ui-image target and containerized UI builds

src/components/Contribute/Knowledge/knowledge.css
=> Increase the wizard component height

src/components/YamlCodeModal/index.tsx
Adds back into view the copy and close buttons.
=> Fix view code modal from PF6 breakage

.env.github.example, .github/workflows/pr-healthcheck-sidecar-image.yml, .gitignore, Makefiles/containers-base/Makefile, Makefiles/local/Makefile, deploy/k8s/base/healthcheck-sidecar/kustomization.yaml, deploy/k8s/base/healthcheck-sidecar/service.yaml, deploy/k8s/overlays/kind/kustomization.yaml, deploy/k8s/overlays/openshift/common/kustomization.yaml, deploy/k8s/overlays/openshift/prod/kustomization.yaml, deploy/k8s/overlays/openshift/qa/kustomization.yaml, docs/healthcheck_sidecar.md, healthcheck-sidecar/Containerfile, healthcheck-sidecar/requirements.txt, healthcheck-sidecar/sidecar_script.py, healthcheck-sidecar/stubbed_model_server.py, src/Containerfile, src/healthcheck-probe.sh
Addresses: #327 
Also includes backward compatibility of podman and docker as container runtime engines. It doesn't include creation of the kind cluster itself, as running KIND (kubernetes in docker) on podman from the CLI, while not impossible, is not trivial.
=> implementing healthcheck sidecar and probe

next-env.d.ts, src/app/api/native/git/branches/route.ts, src/app/api/native/git/knowledge-files/route.ts, src/app/api/native/upload/route.ts, src/app/login/githublogin.tsx, src/app/playground/chat/page.tsx, src/app/playground/endpoints/page.tsx, src/components/AppLayout.tsx, src/components/Contribute/Knowledge/Github/DocumentInformation/DocumentInformation.tsx, src/components/Contribute/Knowledge/Github/index.tsx, src/components/Contribute/Knowledge/Native/DocumentInformation/DocumentInformation.tsx, src/components/Contribute/Knowledge/Native/KnowledgeQuestionAnswerPairsNative/KnowledgeQuestionAnswerPairs.tsx, src/components/Contribute/Knowledge/Native/KnowledgeSeedExampleNative/KnowledgeSeedExampleNative.tsx, src/components/Contribute/Knowledge/Native/index.tsx, src/components/Contribute/Knowledge/ReviewSubmission/index.tsx, src/components/Contribute/Knowledge/UploadFile.tsx, src/components/Contribute/Skill/AttributionInformation/AttributionInformation.tsx, src/components/Contribute/Skill/Github/index.tsx, src/components/Contribute/Skill/Native/index.tsx, src/components/Contribute/Skill/SkillsInformation/SkillsInformation.tsx, src/components/Contribute/Skill/SkillsSeedExample/SkillsSeedExample.tsx, src/components/Dashboard/Github/dashboard.tsx, src/components/Dashboard/Native/dashboard.tsx, src/components/GithubAccessPopup/index.tsx, src/components/PathService/PathService.tsx, src/components/YamlCodeModal/index.tsx, src/types/index.ts, src/utils/devlog.ts
- Adds routes for retrieving files from the local knowledge git
- Adds the ability to view the file changes/additions in the native dashboard.
- Enables the user to view the knowledge document, highlight the text they want to add to the context field and submit it. The highlighted text will get populated to the context field.
- Allows the user to still manually enter context or knowledge file details and handles the state switching when they choose to do so.
- Prevents the user from selecting context from a different commit SHA if they have already selected context from another SHA.
- Lets the user toggle all files in the knowledge files repo if they wanted to use a different file/SHA for context if they want to. Otherwise, the default is the latest commit. Probably the ideal scenario …
=> Add knowledge form context selection

.env.github.example, src/components/Contribute/Knowledge/KnowledgeQuestionAnswerPairs/KnowledgeQuestionAnswerPairs.tsx
- Was checking character counts instead of word counts.
- Also adds a counter for the user to see when over and how much.
- Added user/pass for dev mode in the GitHub env.example.
@vishnoianil Also `npm run pretty` changed a bunch of formatting so I think a PR slid in that didn't get prettied or another version ¯\_(ツ)_/¯ I think that was on me for merging the import cleanups.
Closes #462
=> Change the context limit from characters to words

src/components/Contribute/Knowledge/Native/index.tsx
- seed_examples validation is broken. This is a temp fix for native mode until #465 gets resolved.
=> Disable seed example check on native yaml qna file upload

README.md, docs/development.md
- Add the commands to copy example .env files.
=> Add a docs link to the main readme and .env init example

src/components/Contribute/Knowledge/Native/DocumentInformation/DocumentInformation.tsx, src/components/Contribute/Knowledge/Native/KnowledgeQuestionAnswerPairsNative/KnowledgeQuestionAnswerPairs.tsx
- Native submissions neeed /taxonomy-knowledge-docs appended  to the path after NEXT_PUBLIC_LOCAL_TAXONOMY_ROOT_DIR
- Since knowledge docs are not just a URL, change the validation to text instead of url.
=> Bug fix: fix the knowledge doc repo path and repo url/path validation

pathservice/Containerfile, src/Containerfile
cc @nerdalert and @vishnoianil, this is how downstream will override the `registry.access.redhat.io` images with `registry.redhat.io` `rhel` based images
=> allow images to be overrideable via args

.env.native.example, src/app/api/native/convert/route.ts, src/components/Contribute/Knowledge/Native/DocumentInformation/DocumentInformation.tsx, src/components/Contribute/Knowledge/Native/KnowledgeQuestionAnswerPairsNative/KnowledgeQuestionAnswerPairs.tsx, src/components/Contribute/Knowledge/Native/index.tsx, src/components/Contribute/Knowledge/UploadFile.tsx
- Integrates an automated file conversion via docling-serve to the native knowledge submission component.
- Supports the docling conversion file types of PDF, DOCX, PPTX, XLSX, Images, HTML and AsciiDoc to be used in the next step of context selection (see demo vid below).
- There is a health check of docling-serve at file upload selection, if the service is unavailable, only md files are accepted.
This depends on #439. That PRs changes are in this PR to spare myself another rebase. Will leave this in draft until 439 merges.
Demo .pptx conversion:
https://github.com/user-attachments/assets/e7558b59-79e5-4d48-a23d-877000c7d94d
Demo Image conversion:
https://github.com/user-attachments/assets/d4211702-c23b-4488-8455-fa52cc3e42e4
=> Add a docling service file conversion feature

api-server/.gitignore, api-server/handlers.go, api-server/jobs.go, api-server/main.go
Enables the user to leave and return to the model chat eval without having launch a new job, instead use the existing job for either pre-train or post-train.
=> Add any served models in a column in the jobs table

.github/workflows/cherry-pick.yml
The `-m 1`  option should tell Git to use the first parent of the merge commit as the mainline. Typically the target branch of the original pull request.
=> potential fix for the cherry pick git actions workflow error

api-server/README.md, api-server/rhelai-install/install-glibc-devel.sh, api-server/rhelai-install/install-go.sh, api-server/rhelai-install/rhelai-install.sh
cc @nerdalert and @vishnoianil, will need to start testing this on a RHEL-AI box
=> installing the RHEL-AI api-server via script

api-server/.gitignore, api-server/convert-model.go, api-server/main.go
api-server changes for post-training model conversion to gguf for macOS hosts.
=> Add a convert endpoint for OSX llama.cpp serving of gguf models

src/components/Contribute/Knowledge/index.tsx, src/components/Contribute/Knowledge/knowledge.css, src/components/Contribute/Skill/index.tsx, src/utils/github.ts
Auth session keeps information from the user profile, so if the email address is not made visible on the profile or alias is set as an email address, UI was using that email address for signoff. In some cases, this was failing because that email address is not users primary email address.
For DCO to pass, user needs to signoff the commits with it's primary email address set in his account.
=> Fixes DCO signoff issue

deploy/podman/native/instructlab-ui.yaml
Once UI moves to new docling-serve api's, docling-serve latest image can be used.
=> User the release-alpha image that uses the old docling api

Makefiles/containers-base/Makefile, Makefiles/deployment/kind/Makefile, Makefiles/deployment/openshift/prod/Makefile, Makefiles/deployment/openshift/qa/Makefile, Makefiles/devcontainer/Makefile, Makefiles/linting/Makefile, Makefiles/local/Makefile, Makefiles/podman-compose/Makefile
=> Remove help function from individal Makefile to fix

src/components/Contribute/Knowledge/ReviewSubmission/index.tsx, src/components/Contribute/Skill/Github/index.tsx, src/components/Contribute/Skill/Native/index.tsx, src/components/Contribute/Skill/ReviewSubmission/index.tsx, src/components/Contribute/Skill/ReviewSubmission/submission.css
fixes https://github.com/instructlab/ui/issues/523
Summary of changes on both skill and knowledge review sections:
- Update typography across the review submission step (font styles, and sizes) o
- Added content changes as requested in the figma
- Updated seed data nested component to display accordion style UX
- Updated component with semantic HTML
Screen recording ZIP:
[instructlab.mov.zip](https://github.com/user-attachments/files/18773796/instructlab.mov.zip)
=> 523: UI updates for the submission steps on "Skill" & "Knowledge" Review forms

src/app/api/native/convert-http/route.ts
- Provides the client side a server side route to send docling conversion requests from a URL source rather than file file sources.
Example usage from the client side:
```typescript
const res = await fetch('/api/native/convert-http', {
method: 'POST',
headers: { 'Content-Type': 'application/json' },
body: JSON.stringify({
options: {
from_formats: ['docx', 'pptx', 'html', 'image', 'pdf', 'asciidoc', 'md', 'xlsx'],
to_formats: ['md'],
image_export_mode: 'placeholder',
table_mode: 'fast',
abort_on_error: false,
return_as_file: false,
do_table_structure: true,
include_images: false
},
http_sources: [{ url: 'https://arxiv.org/pdf/2206.01062' }]
})
});
```
cc/ @jeff-phillips-18
=> Add a convert from URL server side rendered route

.env.native.example
- Change from 8000 to 5001 per the current docling-serve default port for the service.
- Add a comment to `NEXT_PUBLIC_TAXONOMY_ROOT_DIR` that it is a required field. Cannot make it dynamic at the moment since it conflicts with the container deployment otherwise.
=> Native mode ENV updates

src/components/Contribute/EditKnowledge/github/EditKnowledge.tsx, src/components/Contribute/EditSkill/github/EditSkill.tsx
When editing a contribution in github mode, if the user loses focus from the current window and then comes back, any edits made are lost.
Update the dependencies that fetch the edit data and update the form to be more specific so that it isn't recreated unless the real data changed.
=> Fix for resetting to edit data in github mode

src/components/Contribute/Knowledge/KnowledgeSeedExamples/KnowledgeSeedExamples.tsx, src/components/Contribute/Knowledge/KnowledgeWizard/KnowledgeWizard.tsx, src/components/Contribute/Skill/SkillWizard/SkillWizard.tsx, src/components/Contribute/Utils/seedExampleUtils.ts
Fixes a bug where the context files are not shown in the select context modal for the first seed example.
Fixes a bug where the selected text does not fill the context input.
Addresses an issue where the wizard form data could be inadvertently reset.
=> Fix for showing context files for the first seed example and filling context from selection

README.md, installers/podman/README.md
Add a new README file in installers/podman to show how to start up the UI locally at localhost:3000
using installers/podman/ilab-ui-native-installer.sh
=> docs: Add local installation instructions

src/components/Contribute/Utils/uploadUtils.ts
Fixes an issue where if you use the upload yaml to fill the skill form, seed example fails validation, even though question/answer pairs are filled.
=> Valid seed examples when uploading a skill yaml file

src/app/api/auth/[...nextauth]/route.ts, src/app/login/githublogin.tsx
I added an inline error message to the login page for an invalid github token as shown in the image. Fixes issue #454
=> Added alert to login page for invalid github token

src/components/Chat/ChatBotComponent.tsx, src/components/Chat/ChatBotContainer.tsx, src/components/Chat/modelService.ts
Fixes the submission to the server side chat fetch to correctly set the `question` field for the submission body.
Cleans up a couple console errors that occur if the user stops the submission.
=> Fix for granite chat submission

src/app/api/convert-http/route.ts, src/app/api/convert/route.ts, src/components/Contribute/Knowledge/FileConversionModal.tsx, src/components/Contribute/Knowledge/UploadFromGitModal.tsx
Both of these api's are not specific to only native mode. These api's are used across both the mode so it makes sense for them to be out of specific mode api's.
=> Move convert and conver-http api out of native directory

api-server/vllm-serve.go
- The vllm-status api call was filtering on the old `openai/vllm` image that has been migrated to the ilab image. Resolves any issues with `curl -X GET http://localhost:8080/vllm-containers` showing null when there are vllm instances.
=> Change podman vllm filter to the ilab image

api-server/vllm-serve.go
Resolves the vllm status check issue.
=> Use the model path from the positional model name

src/components/Contribute/Knowledge/KnowledgeSeedExamples/KnowledgeFileSelectModal.tsx, src/components/Contribute/Knowledge/KnowledgeSeedExamples/KnowledgeSeedExampleCard.tsx, src/components/Contribute/Knowledge/KnowledgeSeedExamples/KnowledgeSeedExamples.scss, src/components/Contribute/Knowledge/KnowledgeWizard/KnowledgeWizard.tsx, src/components/Contribute/ReviewSubmission/ReviewSubmission.tsx, src/components/Contribute/Skill/SkillWizard/SkillWizard.tsx, src/components/Contribute/Utils/seedExampleUtils.ts, src/components/Contribute/Utils/validationUtils.ts
Change error visuals/text to warnings for seed example word counts. Allow saving when over the recommended word count limits.
Update the seed example validations when reaching the review step so that errors are shown correctly when navigating back to the seed example step.
/cc @kaedward
=> Update word count overage to a warning rather than error

api-server/rhelai-install/rhelai-install.sh, src/app/api/playground/chat/route.ts, src/app/playground/endpoints/DeleteEndpoinModal.tsx, src/app/playground/endpoints/EditEndpointModal.tsx, src/app/playground/endpoints/EndpointActions.tsx, src/app/playground/endpoints/page.tsx, src/components/AppLayout.tsx, src/components/Chat/ChatBotComponent.tsx, src/components/Chat/ModelsContext.tsx, src/components/Chat/modelService.ts, src/components/Experimental/ChatEval/ChatEval.tsx, src/types/index.ts
Resolves #460 
Updates the UI design for the `Custom model endpoints` page.
/cc @Misjohns @kaedward
=> Custom model endpoint redesign

src/components/AppLayout.tsx, src/components/Contribute/Knowledge/KnowledgeSeedExamples/KnowledgeQuestionAnswerPair.tsx, src/components/Contribute/Knowledge/KnowledgeSeedExamples/KnowledgeSeedExamples.scss
Fix to typo in the `Experimental features` nav item.
Fix text overwrite for long text in q&a text areas
=> Fix typo in Experimental features nav item and q&a text overwrite

src/app/contribute/skill/page.tsx
Seems like skill page renders before deployment type is set and that results in loading SkillFormGithub, and that eventually calls the /api/github/tree api's. Once the deployment type value is set, it renders the SkillFormNative. Calling of /api/github/tree, overwrite the taxonomy if it sees that the remote sha is not same as local sha. This is expected because in case of the github mode local taxonomy is only read only, and it clones the latest taxonomy if remote sha is not equal to local sha. But in native mode, local taxonomy is used for caching the submitted contribution as well, so it doesn't have to pull any new changes upstream because call the taxonomy changes are in the scope of single user and that too present on the same machine. But in both the mode, local taxonomy is store at …
=> Fix taxonomy deletion on skill wizard loading

src/components/Contribute/Utils/autoSaveUtils.ts, src/components/Dashboard/Github/dashboard.tsx, src/components/Dashboard/Native/dashboard.tsx
- Add "Delete draft" option to delete the draft changes for existing contributions
- Add label "New submission" for in progress contribution and "Existing Submission" to already submitted contribution
- Add warning modal to confirm deletion of draft and submitted contribution
- In Native mode, Disable "Publish contribution", "Download taxonomy" and "Delete contribution" when the existing contribution is in draft state.
- In Github mode, Disable "Download taxonomy" when the existing contribution is in draft state.
- Show "Delete draft" and "Delete Contribution" in Red color and separated by divider.
=> Improve the user experience for managing the drafts

.github/dependabot.yml, .github/mergify.yml, .github/workflows/cherry-pick.yml, .github/workflows/lint-jobs.yml, yamllint.yaml
Some of the YAML configurations are inconsistent and/or incorrect (and are not being actively parsed). Example invalid config for Dependabot:
Therefore, the Dependabot updates we want are not properly being triggered.
- Fixed the Dependabot config
- Updated the mergify config to have uniform formatting 
- Added a new lint check to lint YAML files in the `.github` directory. (Other directories are out of scope for this PR, but we can lint and fix other broken YAML files in a follow-up PR.)
- Added a yamllint config so we can configure how we want yamllint to behave in the above lint check.
=> fix: Mergify and Dependabot configs YAML are incorrect/inconsistent

src/app/api/github/tree/route.ts
Ensure that taxonomy is locally clone before
checking for the updates.
=> Fix github tree api for startup scenario

src/components/Contribute/ContributionWizard/DetailsPage/DetailsPage.tsx, src/components/Contribute/Knowledge/KnowledgeWizard/KnowledgeWizard.tsx, src/components/Contribute/Skill/SkillWizard/SkillWizard.tsx
Relates to #787
In this PR we're updating the "Skill Contribution Summary" and "Knowledge Contribution Summary" placeholder texts to have different texts.
Previously, bo used the same text: `"Example: Information about the Phoenix Constellation including the history, characteristics, and features of the stars in the constellation."`
Now, the `ContributionWizard/DetailsPage/DetailsPage.tsx` component accepts a new prop: `submissionSummaryPlaceholder`, replacing the hardcoded text and enabling dynamic customization.
I used the following texts:
Knowledge: `"Describe the main idea or information this example teaches (e.g., defining a scientific term, explaining a historical event)."`
Skill: `"Describe the skill this example helps the model learn (e.g., solving math problems, spotting grammar …
=> Differentiate submission summary placeholder text for Skills and Knowledge contributions

src/app/contribute/skill/[...slug]/page.tsx, src/app/contribute/skill/edit/[...slug]/page.tsx, src/app/contribute/skill/page.tsx, src/app/experimental/chat-eval/page.tsx, src/app/experimental/fine-tune/page.tsx, src/app/playground/chat/page.tsx, src/app/playground/endpoints/page.tsx, src/components/AppLayout.tsx, src/components/Banner/DevFlagsBanner.tsx, src/context/FeatureFlagsContext.tsx
Adds the ability to enable all feature flags by adding `?devFeatureFlags` (`&devFeatureFlags` if search params already exist) to the URL.
Adds checks to ensure pages that are disabled are not shown if the user happens to know the URL to the page.
When On a banner is shown indicating the feature flags have been enabled and a button to turn the feature flags back to their original state (from the .env file).
=> Add ability to turn on feature flags via search param 'devFeatureFlags'

src/app/contribute/knowledge/[...slug]/page.tsx, src/app/contribute/knowledge/edit/[...slug]/page.tsx, src/app/contribute/skill/[...slug]/page.tsx, src/app/contribute/skill/edit/[...slug]/page.tsx, src/app/dashboard/page.tsx, src/app/documents/page.tsx, src/app/experimental/chat-eval/page.tsx, src/app/experimental/fine-tune/page.tsx, src/app/index.tsx, src/components/Contribute/ContributePageHeader.tsx, src/components/Contribute/Knowledge/Edit/EditKnowledge.tsx, src/components/Contribute/Knowledge/Edit/KnowledgeForm.tsx, src/components/Contribute/Knowledge/KnowledgeFormActions.tsx, src/components/Contribute/Knowledge/View/ViewKnowledge.tsx, src/components/Contribute/Knowledge/View/ViewKnowledgePage.tsx, src/components/Contribute/Skill/Edit/EditSkill.tsx, src/components/Contribute/Skill/Edit/SkillForm.tsx, src/components/Contribute/Skill/SkillFormActions.tsx, src/components/Contribute/Skill/View/ViewSkill.tsx, src/components/Contribute/Skill/View/ViewSkillPage.tsx, src/components/Contribute/Utils/autoSaveUtils.ts, src/components/Dashboard/ContributionActions.tsx, src/components/Dashboard/ContributionCard.tsx, src/components/Dashboard/ContributionTableRow.tsx, src/components/Dashboard/DashboardPage.tsx, src/types/index.ts
- Removes the need for the `isDraft` query item in the URL.
- View/Edit pages check for a draft and use it if found.
- Updates the draft save/create based on changes to the current contribution/draft. This removes drafts that do not differ from the submitted contribution.
=> Simplify navigation for draft contributions
