instructlab/ui

- .github/workflows/images.yml
- Makefile
> Publish ui container image to ghcr.io

- src/app/edit-submission/knowledge/[id]/page.tsx
- src/app/edit-submission/skill/[id]/page.tsx
> Fix edit submissions to not add single quotes in edited QA fields

- package.json
relates to: https://instruct-lab.slack.com/archives/C076C9RNKSA/p1720724970098319
Fixes #67
> promote js-yaml from devDependencies

- src/app/playground/chat/page.tsx
** This needs to be reviewed and merged after https://github.com/instructlab/ui/pull/79 **
Here I have added logic and an alert to indicate to a user when they have attempted to send a chat request with no question/prompt.
Fixes #78 
Depends-on #79
> Chat request with no prompt

- src/app/api/playground/chat/route.ts
- src/components/Contribute/Knowledge/UploadFile.tsx
- Temporary until doc conversion is live.
> Change the accepted filetype msg to Markdown only

- src/components/Contribute/Knowledge/index.tsx
We anticipate that this will be the main route of entry for most users.
> Swapping the automatic documant upload with the manual upload. 

- src/app/edit-submission/knowledge/[id]/page.tsx
- src/components/Contribute/Knowledge/index.tsx
- src/types/index.ts
- Schema can be viewed at: https://github.com/instructlab/schema/blob/main/src/instructlab/schema/v3/
Closes #87
> Update knowledge submissions and edits to the v3 schema

- src/components/Contribute/Skill/SkillDescription.tsx
Change "foudational" to "foundational"
> Fix typo in SkillDescription.tsx

- src/utils/validation.ts
addressing issue : Adjust error message #66
> adjust error message to be more clear

- src/components/GithubAccessPopup/index.tsx
> Minor updates to the github access popup warning message

- src/components/Contribute/Knowledge/DocumentInformation/DocumentInformation.tsx
- src/components/Contribute/Knowledge/DownloadAttribution/DownloadAttribution.tsx
- src/components/Contribute/Knowledge/DownloadDropdown/DownloadDropdown.tsx
- src/components/Contribute/Knowledge/DownloadYaml/DownloadYaml.tsx
- src/components/Contribute/Knowledge/UploadFile.tsx
- src/components/Contribute/Knowledge/ViewDropdown/ViewDropdown.tsx
- src/components/Contribute/Knowledge/index.tsx
- src/components/Contribute/Knowledge/knowledge.css
- Add Download dropdown menu, to club Download Yaml and Attribution
- Add View dropdown menu to club View Yaml and View Attribution
- Show warning of data loss when user switch between "Automatic Upload Documents" and "Manually Enter Document Details" or vice versa.
- Only allow markdown files for knowledge doc upload.
FIxes #119 
Fixes #139
Implements some of the suggestions provided in #117
> Knowledge improvements

- package-lock.json
- package.json
* types should be a dev dependency
* typescript should also be a dev dep
> chore: update dev deps

- src/app/api/pr/knowledge/route.ts
- src/app/edit-submission/knowledge/[id]/page.tsx
- src/components/Contribute/Knowledge/AttributionInformation/AttributionInformation.tsx
- src/components/Contribute/Knowledge/DocumentInformation/DocumentInformation.tsx
- src/components/Contribute/Knowledge/FilePathInformation/FilePathInformation.tsx
- src/components/Contribute/Knowledge/KnowledgeInformation/KnowledgeInformation.tsx
- src/components/Contribute/Knowledge/Update/Update.tsx
- src/components/Contribute/Knowledge/index.tsx
- src/components/PathService/PathService.tsx
- src/utils/github.ts
Use the same knowledge form for edit, that is used for submitting new knowledge. That way, we don't
have to maintain two version of the form for submit and edit.
> Fix knowledge edit feature

- src/utils/yamlConfig.ts
> Remove trailing new line from the downloaded yaml file

- src/app/playground/chat/chat.module.css
- src/app/playground/chat/page.tsx
- src/app/playground/endpoints/page.tsx
- src/components/Contribute/Knowledge/index.tsx
- src/components/Contribute/Skill/index.tsx
- src/components/Dashboard/index.tsx
> Add header to dashboard, chat, and customer endpoints pages

- src/app/playground/chat/chat.module.css
- Removing the CSS resolves the issue.
Closes #174
> Fix chat box width

- src/components/Dashboard/index.tsx
> Set width to the empty state text

- src/app/login/githublogin.css
- src/app/login/githublogin.tsx
- src/components/AboutModal/AboutModal.tsx
- src/components/Contribute/Knowledge/KnowledgeDescription/KnowledgeDescriptionContent.tsx
- src/components/Contribute/Knowledge/KnowledgeSeedExample/KnowledgeSeedExample.tsx
- src/components/Contribute/Knowledge/Update/Update.tsx
- src/components/Contribute/Knowledge/index.tsx
- src/components/Contribute/Skill/Update/Update.tsx
- Add help links from docs.instructlab.ai for skill
- Add private policy and terms of use to the login page
- Fix rendering of the error messages
> Fix minor issues related to beta release

- deploy/k8s/overlays/openshift/prod/kustomization.yaml
- src/components/Contribute/Knowledge/index.tsx
Knowledge submission was not enabling the submit button once any validation error occur, even if after correction of error.
Also updated the manifest for prod to use the latest tag. latest tag points to the latest release.
> Fix knowledge submission issue

- next-env.d.ts
- src/components/AppLayout.tsx
Cherry-pick pe #217 from main to release-1.0
> Adjust flex layout to avoid help and avatar stacking in masthead

- .github/workflows/cherry-pick.yml
Cherry-pick will be triggered once branch is merged and it's labelled cherry-pick-release-1.0.
> Add workflow to auto cherry-pick PR to release branch release-1.0

- src/components/AppLayout.tsx
- The header and left sidebar of the application are not responsive, causing layout issues and reduced usability on smaller window sizes and mobile devices
- Update Patternfly components to make use of the built-in responsive capabilities for header and sidebar.
https://github.com/user-attachments/assets/6babfaec-6f01-406f-810e-f08b83196a5a
> 194: Improve responsive behavior of Header and Side Navigation Bar

- .github/workflows/cherry-pick.yml
> Fix permission for cherry-pick workflow

- src/app/login/githublogin.css
> cherry-pick: Update login page background responsiveness

- docs/development.md
This is temporary until QA and Dev are automated.
Fixes #262
> Add cherry pick instructions to the dev docs

- src/app/login/githublogin.tsx
Changed the headline and text in content area of the Join InstructLab on GitHub modal.
> Updated microcopy on the Join InstructLab on GitHub modal

- src/components/Contribute/AuthorInformation.tsx
- src/components/Contribute/Knowledge/AttributionInformation/AttributionInformation.tsx
- src/components/Contribute/Knowledge/DocumentInformation/DocumentInformation.tsx
- src/components/Contribute/Knowledge/KnowledgeInformation/KnowledgeInformation.tsx
- src/components/Contribute/Knowledge/KnowledgeQuestionAnswerPairs/KnowledgeQuestionAnswerPairs.tsx
- src/components/Contribute/Knowledge/index.tsx
- src/components/Contribute/Skill/AttributionInformation/AttributionInformation.tsx
- src/components/Contribute/Skill/SkillsInformation/SkillsInformation.tsx
- src/components/Contribute/Skill/SkillsSeedExample/SkillsSeedExample.tsx
- src/components/PathService/PathService.tsx
adding gap between form elements skill and knowledge
improved validation and error messages
closes : https://github.com/instructlab/ui/issues/149
> adding gap between form elements skill and knowledge

- src/components/Contribute/AuthorInformation.tsx
- src/components/Contribute/Knowledge/AttributionInformation/AttributionInformation.tsx
- src/components/Contribute/Knowledge/DocumentInformation/DocumentInformation.tsx
- src/components/Contribute/Knowledge/KnowledgeInformation/KnowledgeInformation.tsx
- src/components/Contribute/Knowledge/KnowledgeQuestionAnswerPairs/KnowledgeQuestionAnswerPairs.tsx
- src/components/Contribute/Knowledge/index.tsx
- src/components/Contribute/Skill/AttributionInformation/AttributionInformation.tsx
- src/components/Contribute/Skill/SkillsInformation/SkillsInformation.tsx
- src/components/Contribute/Skill/SkillsSeedExample/SkillsSeedExample.tsx
- src/components/PathService/PathService.tsx
closes : https://github.com/instructlab/ui/issues/149
> Cherry-picking: Improve from elements across GUI 

- src/components/HelpDropdown/HelpDropdown.tsx
- This is surfacing an error with next.js 15
> Bug: use unique keys in in the help dropdown

- src/components/HelpDropdown/HelpDropdown.tsx
- This is surfacing an error with next.js 15
> Cherry Pick: Bug: use unique keys in in the help dropdown

- .github/workflows/pr-images.yml
- .github/workflows/release-images.yml
This should change the commit to come from the `github-actions[bot]`.
> push from github-actions bot

- .github/workflows/pr-images.yml
- pathservice/Containerfile
more fixes for testing
cc @nerdalert @vishnoianil
> more fixes for testing

- .github/workflows/pr-images.yml
cc @vishnoianil @nerdalert 
Global git settings do not exist so debug logging on them fails the action
> logging global git configs fails because dont exist

- src/app/api/local/git/branches/route.ts
- src/components/Contribute/AuthorInformation.tsx
- src/components/Contribute/Knowledge/AttributionInformation/AttributionInformation.tsx
- src/components/Contribute/Knowledge/DocumentInformation/DocumentInformation.tsx
- src/components/Contribute/Knowledge/FilePathInformation/FilePathInformation.tsx
- src/components/Contribute/Knowledge/KnowledgeInformation/KnowledgeInformation.tsx
- src/components/Contribute/Knowledge/KnowledgeQuestionAnswerPairs/KnowledgeQuestionAnswerPairs.tsx
- src/components/Contribute/Knowledge/KnowledgeSeedExample/KnowledgeSeedExample.tsx
- src/components/Contribute/Skill/SkillsSeedExample/SkillsSeedExample.tsx
- src/components/Experimental/ContributeLocal/Knowledge/index.tsx
- src/components/Experimental/ContributeLocal/Knowledge/knowledge.css
- src/components/Experimental/DashboardLocal/index.tsx
- src/components/Experimental/ReviewSubmission/index.tsx
Initial stepped style for local knowledge submissions
Closes #343 
https://github.com/user-attachments/assets/6ecaeb57-fb2d-485a-9f37-0f069b60df74
> Convert standalone knowledge submissions to the new stepped style

- README.md
labels to use to tag the production related issues
> Updated readme with details of hosted instance and

- .github/workflows/pr-images.yml
This PR is non invasive fixes already broken CI. cc @vishnoianil
> FIXING CI: make sure to access step output in github action syntax

- LICENSE
> apply our license

- src/components/AppLayout.tsx
- src/components/Contribute/Knowledge/DownloadAttribution/DownloadAttribution.tsx
- src/components/Contribute/Knowledge/DownloadDropdown/DownloadDropdown.tsx
- src/components/Contribute/Knowledge/DownloadYaml/DownloadYaml.tsx
- src/components/Contribute/Knowledge/ViewDropdown/ViewDropdown.tsx
- src/components/Dashboard/Github/dashboard.tsx
> PF cleanup: general notes, issue #369

- .github/workflows/pr-images.yml
TSIA.
Issue visable here: https://github.com/instructlab/ui/actions/runs/12313887731/job/34368872774#step:16:5
> [FIX]  QA publish pathservice job now updates its own image

- .github/workflows/pr-images.yml
> include registry prefix in yq command

- src/app/api/envConfig/route.ts
- src/app/api/native/clone-repo/route.ts
- src/app/api/native/git/branches/route.ts
- src/app/api/native/upload/route.ts
- src/app/api/tree/route.ts
- src/components/Dashboard/Native/dashboard.tsx
- src/components/PathService/PathService.tsx
Fixed document upload for scenarios where docs needs to be mounted from host in container environment.
> Fix PathService selection issue

- deploy/podman/README.md
- deploy/podman/native/instructlab-ui.yaml
and troubleshooting instruction for the UI stack deployment on rootless podman and SELinux environment
> Updated manifest file and readme to include installation issues

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
Implementation of feature request templates to help users bootstrap requests.
> feature request template

- next-env.d.ts
- src/app/api/native/clone-repo/route.ts
- src/app/api/native/git/branches/route.ts
- src/app/api/native/pr/knowledge/route.ts
- src/app/api/native/pr/skill/route.ts
- src/app/api/native/upload/route.ts
- src/components/Contribute/Knowledge/Github/DocumentInformation/DocumentInformation.tsx
- src/components/Contribute/Knowledge/Github/index.tsx
- src/components/Contribute/Knowledge/Native/DocumentInformation/DocumentInformation.tsx
- src/components/Contribute/Knowledge/Native/index.tsx
- src/components/Contribute/Knowledge/UploadFile.tsx
- src/components/Contribute/Skill/Github/index.tsx
- src/components/Contribute/Skill/Native/index.tsx
- src/components/Dashboard/Native/dashboard.tsx
- Fix skill contribution yaml file formatting.
- Improve console logging for capturing better debug logs
- Removed inline alerts and moved them to top right corner in toast alert stype.
- Throw warning alert if contribution publishing fails.
- Fix formatting of the knowledge success alert.
- Show alert if the knowledge related docs are  successfully uploaded
- Move Auto-fill to top corner near "Upload a YAML file" for both Native and Github mode
- Enable "Upload a YAML file" option for native mode
> PR contains following minor bug fixes:

- src/components/HelpDropdown/HelpDropdown.tsx
Hi, I think I accidentally closed the previous pull request. This is for issue #476. I increased the size of the help icon and made the dropdown appear again. Let me know if there are any issues.
Fixes #476
> Fixed help dropdown and made help icon larger

- src/app/login/githublogin.css
> Enlarge the login text and adjust the color

- src/app/login/page.tsx
The page was rendering prior to the useEffect finishing fetching environment data and throwing the hydration mismatched html on the client.
> Fix the hydration error on the login page

- src/app/playground/chat/page.tsx
- src/app/playground/endpoints/page.tsx
- src/components/Contribute/Knowledge/Native/DocumentInformation/DocumentInformation.tsx
- Knowledge document upload/success notification is shown in top right now
- Fix the styling of custom endpoint page
- Chat related error notification are show in top right.
> Minor UI fixes in knowledge form, chat and custom endpoint pages

- docs/development.md
Let me know if this is enough explanation.
> explaining how to update the sealed secret

- argocd/overlays/applicaitons/kustomization.yaml
- argocd/overlays/applicaitons/prod.yaml
cc @vishnoianil Starting the prod process
> onboard instructlab-prod to argocd

- deploy/k8s/overlays/openshift/prod/kustomization.yaml
cc @vishnoianil  this should fix our issue by removing the sidecar from prod
> removing healthcheck-sidecar from prod

- deploy/k8s/overlays/openshift/prod/kustomization.yaml
> add back secret name replace for prod

- src/app/playground/chat/page.tsx
fixes https://github.com/instructlab/ui/issues/257
- Updated text and removed "Model Selector"
- Chat area change to "Enter a question…"
> Updates to playground chat page per design review

- installers/podman/ilab-ui-native-installer.sh
- Fix usage messages
- Enable experimental features for native mode if ilab is setup on the host
- Fix taxonomy path (removing front, tail spaces and LF/CR char
> Minor fixes in the UI native installer

- src/app/api/native/pr/knowledge/route.ts
- src/app/api/native/pr/skill/route.ts
- src/components/Contribute/Knowledge/DownloadDropdown/DownloadDropdown.tsx
- src/components/Contribute/Knowledge/Github/Submit/Submit.tsx
- src/components/Contribute/Knowledge/Github/Update/Update.tsx
- src/components/Contribute/Knowledge/Github/index.tsx
- src/components/Contribute/Knowledge/Native/Submit/Submit.tsx
- src/components/Contribute/Knowledge/Native/Update/Update.tsx
- src/components/Contribute/Knowledge/Native/index.tsx
- src/components/Contribute/Knowledge/ReviewSubmission/index.tsx
- src/components/Contribute/Knowledge/ViewDropdown/ViewDropdown.tsx
- src/components/Contribute/Knowledge/validation.tsx
- src/components/Contribute/Skill/DownloadDropdown/DownloadDropdown.tsx
- src/components/Contribute/Skill/Github/Submit/Submit.tsx
- src/components/Contribute/Skill/Github/Update/Update.tsx
- src/components/Contribute/Skill/Github/index.tsx
- src/components/Contribute/Skill/Native/Submit/Submit.tsx
- src/components/Contribute/Skill/Native/Update/Update.tsx
- src/components/Contribute/Skill/Native/index.tsx
- src/components/Contribute/Skill/ReviewSubmission/index.tsx
- src/components/Contribute/Skill/ViewDropdown/ViewDropdown.tsx
- src/components/Contribute/Skill/validation.tsx
This fixes issue #475. I removed the attribution fields from the skill and knowledge sections for native mode.
> Issue #475 - Removed attribution fields from native mode

- src/app/experimental/chat-eval/page.tsx
- src/components/Experimental/ChatEval/ChatEval.tsx
- src/styles/chatbot.scss
Fixes the view logs section for the chat eval
> Fix log view of chat eval

- .github/workflows/release-images.yml
> updating release-images workflow trigger condition to published

- .github/workflows/pr-images.yml
- .github/workflows/release-images.yml
> downgrading runner version

- src/components/Contribute/Knowledge/uploadUtils.ts
- src/components/Contribute/Skill/Native/Submit/Submit.tsx
- src/components/Contribute/Skill/Native/Update/Update.tsx
Use name for knowledge contribution for native mode instead of email address.
> Do not user created_by for Name in Yaml upload feature

- src/components/Contribute/Knowledge/KnowledgeWizard/KnowledgeWizard.tsx
- src/components/Contribute/Knowledge/SeedExamples/KnowledgeFileSelectModal.tsx
- src/components/Contribute/Knowledge/SeedExamples/QuestionAnswerPairs.tsx
- src/components/Contribute/Knowledge/SeedExamples/SeedExamples.tsx
- src/components/Contribute/Knowledge/seedExampleUtils.ts
- src/components/Contribute/Knowledge/validationUtils.ts
- Adds a fix to set the status for the Attribution step in the knowledge wizard
- Adds a fix to properly fill the context input area when selecting context from a file
> Fixes for Attribution step status and filling input box on context selection from a file

- installers/podman/ilab-ui-native-installer.sh
directory is not empty and it's a git initialized repo.
> Normalize the taxonomy path and make sure the taxonomy

- api-server/handlers.go
- Use the maintained instructlab image for api-server inference.
Closes #624
> Replace the image vllm/vllm-openai with instructlab-nvidia

- src/components/Contribute/DetailsPage/DetailsPage.tsx
- src/components/PathService/AddDirectoryModal.tsx
- src/components/PathService/PathService.css
- src/components/PathService/PathService.tsx
Resolves #654 
Resolves #147 
Updates the File Path selection component to use a tree view.
Adds a `Search` capability
Adds the ability to add a subdirectory
> Improve file path selection UX, allow adding sub-directories

- src/components/Contribute/AttributionInformation/AttributionInformation.tsx
- src/components/Contribute/ContributionWizard/ContributionWizard.tsx
- src/components/Contribute/DetailsPage/DetailsPage.tsx
- src/components/Contribute/DetailsPage/EditContributorModal.tsx
- src/components/Contribute/Knowledge/DocumentInformation/DocumentInformation.tsx
- src/components/Contribute/Knowledge/FileConversionModal.tsx
- src/components/Contribute/Knowledge/KnowledgeSeedExamples/KnowledgeFileSelectModal.tsx
- src/components/Contribute/Knowledge/KnowledgeSeedExamples/KnowledgeQuestionAnswerPairs.tsx
- src/components/Contribute/Knowledge/KnowledgeSeedExamples/KnowledgeSeedExamples.tsx
- src/components/Contribute/Knowledge/KnowledgeWizard/KnowledgeWizard.tsx
- src/components/Contribute/Knowledge/UploadFile.tsx
- src/components/Contribute/Knowledge/UploadFromGitModal.tsx
- src/components/Contribute/ReviewSubmission/ReviewSubmission.tsx
- src/components/Contribute/Skill/SkillSeedExamples/SkillQuestionAnswerPairs.tsx
- src/components/Contribute/Skill/SkillSeedExamples/SkillSeedExamples.tsx
- src/components/Contribute/Skill/SkillWizard/SkillWizard.tsx
- src/components/Contribute/Utils/seedExampleUtils.ts
- src/components/Contribute/Utils/validation.ts
Fixes [[Dev] Contribution wizard content updates based on review](https://github.com/instructlab/ui/issues/697)
Update content of contribution wizard screens based on Content design review
/cc @kaedward
> Contribution wizard content updates

- src/app/api/download/route.ts
- src/components/Dashboard/Native/dashboard.tsx
> Add a download taxonomy api and client side dashboard option

- src/components/Contribute/Knowledge/KnowledgeSeedExamples/KnowledgeSeedExamples.tsx
- src/components/Contribute/Skill/SkillSeedExamples/SkillSeedExamples.tsx
- src/components/Contribute/Utils/validationUtils.ts
Fixes validation check for the seed data page.
Fixes the text for adding a seed example button.
> Fix for seed example validation and adding new seed example button

- src/app/api/github/pr/knowledge/route.ts
- src/app/api/github/pr/skill/route.ts
- src/app/edit-submission/knowledge/github/[...slug]/page.tsx
- src/app/edit-submission/knowledge/native/[...slug]/page.tsx
- src/app/edit-submission/skill/github/[...slug]/page.tsx
- src/app/edit-submission/skill/native/[...slug]/page.tsx
- src/components/Contribute/ContributionWizard/ContributionWizard.tsx
- src/components/Contribute/EditKnowledge/github/EditKnowledge.tsx
- src/components/Contribute/EditKnowledge/native/EditKnowledge.tsx
- src/components/Contribute/EditSkill/github/EditSkill.tsx
- src/components/Contribute/EditSkill/native/EditSkill.tsx
- src/components/Contribute/Knowledge/KnowledgeWizard/KnowledgeWizard.tsx
- src/components/Contribute/Skill/SkillWizard/SkillWizard.tsx
- src/components/Contribute/Utils/autoSaveUtils.ts
- src/components/Contribute/Utils/documentUtils.ts
- src/components/Dashboard/Github/dashboard.tsx
- src/components/Dashboard/Native/dashboard.tsx
- src/types/index.ts
In-progress skill and knowledge contribution will be auto-saved and will be shown on dashboard with "draft" label.
If user edits the submitted contribution, it will show the contribution in Draft state as well.
Once the contribution is submitted auto-saved draft will be deleted.
Fixes: #695 #13
> feat:Auto save the in- progress skill and knowledge contribution

- src/app/api/github/tree/route.ts
Ensure that taxonomy is locally clone before
checking for the updates.
> Fix github tree api for startup scenario

- src/app/documents/page.tsx
- src/components/AppLayout.tsx
- src/components/CardView/CardView.tsx
- src/components/Dashboard/ContributionActions.tsx
- src/components/Dashboard/Dashboard.tsx
- src/components/Documents/DeleteDocumentModal.tsx
- src/components/Documents/DocumentActions.tsx
- src/components/Documents/DocumentCard.tsx
- src/components/Documents/DocumentTableRow.tsx
- src/components/Documents/DocumentUploadArea.tsx
- src/components/Documents/Documents.scss
- src/components/Documents/Documents.tsx
- src/components/Documents/DocumentsToolbar.tsx
- src/components/Documents/MarkdownFileViewer.tsx
- src/components/Documents/MultFileUploadArea.tsx
- src/components/Documents/MyDocuments.tsx
- src/components/Documents/UploadExternalDocumentModal.tsx
- src/components/Documents/const.ts
- src/components/Documents/fileConversionUtils.tsx
- src/components/Table/TableBase.tsx
Towards https://github.com/instructlab/ui/issues/727
Adds a `Documents` section to the UI allowing users to upload and manage documents to be used in contributions.
/cc @Misjohns @beaumorley
> Add documents section

- README.md
Community meetings will be held monthly instead of weekly. Update REAME file to reflect the change.
> Update community meeting information
